language: java

jdk:
  - oraclejdk8

after_success:
  - wget mvn http://roboconf.net/resources/build/settings.xml
  - mvn clean deploy -q --settings settings.xml

notifications:
  email:
  - herve.tchepannou@gmail.com
